### ISSUE TITLE
Error tokenizing data

### ISSUE THREAD

**Issue by baccandr** [dhhagan/py-smps#14]
Hi,
thank you very much for this library, I get the following error when trying to open a new SMPS file:

> CParserError: Error tokenizing data. C error: Expected 3 fields in line 3, saw 6

Please note that I'm using the following command: smps.io.load_file(fpath, column=False)
Moreover, I'm working with Python 2.7, maybe this is the problem....

Thank you,
Andrea

**Comment by dhhagan** [comment]
Hi @Zambadeos , that sounds like an error with the file format. Have you tried loading it with both `column=True` and `column=False`? If you have, and the error is still coming up, could you forward the file so I could take a look?

**Comment by dhhagan** [comment]
@Zambadeos FYI, it looks like from time-to-time, the SMPS spits out a poorly written file where some of the columns have an incorrect number of rows. I don't know why, but it happens. I am making some updates now that will fix it.

**Comment by Zambadeos** [comment]
Thanks @dhhagan and sorry for this late reply. I tried to change the column argument but didn't solve the problem. However if I read the SMPS file with pandas read_csv function everything is ok! Attached a small example file so you can have a look...
by the way I'm not in a hurry so don't worry if you cannot solve this now...
thanks a lot 
[170727_TSI.txt](https://github.com/dhhagan/py-smps/files/1245659/170727_TSI.txt)

**Comment by dhhagan** [comment]
Ahh okay. It looks like there is some weird stuff going on with the number of columns per line in the meta information. I'm not sure why AIM is doing that...
